import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { getFirestore, collection, doc, onSnapshot, getDocs, setDoc, addDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBCYpQcTm0_37GAUy8FK_vfChk8seFCOKI",authDomain:"mcgriffsrental.firebaseapp.com",projectId:"mcgriffsrental",storageBucket:"mcgriffsrental.firebasestorage.app",messagingSenderId:"511623270295",appId:"1:511623270295:web:d326c6fd852bafa2e6fed2"};
const app=initializeApp(firebaseConfig);const auth=getAuth(app);const db=getFirestore(app);
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const profiles={owner:{name:"Mike Roquet",email:"cody.dezwarte+owner@gmail.com",role:"owner"},manager:{name:"Cody DeZwarte",email:"cody.dezwarte@gmail.com",role:"manager"}};
const state={equipment:[],customers:[],rentals:[],reservations:[],maintenance:[],settings:{},profile:null,view:"dashboard",search:""};let selectedProfile=null;

function toast(message){$("toast").textContent=message;$("toast").classList.remove("hidden");clearTimeout(window.__toast);window.__toast=setTimeout(()=>$("toast").classList.add("hidden"),2200)}
function openModal(title,html){$("modalTitle").textContent=title;$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
function fmt(v){if(!v)return"";const d=v?.toDate?v.toDate():new Date(v);return isNaN(d)?String(v):d.toLocaleString()}
function activeRental(id){return state.rentals.find(r=>r.equipmentId===id&&!r.actualReturnAt)}
function activeReservation(id){return state.reservations.filter(r=>r.equipmentId===id&&String(r.status||"").toLowerCase()!=="cancelled"&&new Date(r.endAt||r.startAt||0)>=new Date()).sort((a,b)=>new Date(a.startAt||0)-new Date(b.startAt||0))[0]}
function equipmentStatus(e){if(String(e.status||"").toLowerCase()==="maintenance"||e.inMaintenance)return"Maintenance";if(activeRental(e.id))return"Rented";if(activeReservation(e.id))return"Reserved";return"Available"}
function imageUrl(url){const text=String(url||"");const m=text.match(/[?&]id=([^&]+)/i)||text.match(/\/d\/([^/?#]+)/i);return m?`https://lh3.googleusercontent.com/d/${encodeURIComponent(m[1])}=w1200`:text}

function setView(view){state.view=view;document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(`${view}View`)?.classList.remove("hidden");document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===view));const labels={dashboard:["Dashboard","Clean V6 foundation"],equipment:["Equipment","Inventory and customer resources"],customers:["Customers","Customer records"],rentals:["Rentals","Active and completed rentals"],reservations:["Reservations","Upcoming bookings"],maintenance:["Maintenance","Service and repair records"]};$("pageTitle").textContent=labels[view]?.[0]||view;$("pageSubtitle").textContent=labels[view]?.[1]||""}

function render(){renderDashboard();renderEquipment();renderCustomers();renderRentals();renderReservations();renderMaintenance()}
function renderDashboard(){const statuses=state.equipment.map(e=>equipmentStatus(e));$("kpiEquipment").textContent=state.equipment.length;$("kpiAvailable").textContent=statuses.filter(x=>x==="Available").length;$("kpiRented").textContent=statuses.filter(x=>x==="Rented").length;$("kpiReserved").textContent=statuses.filter(x=>x==="Reserved").length;$("kpiMaintenance").textContent=statuses.filter(x=>x==="Maintenance").length;
 const active=state.rentals.filter(r=>!r.actualReturnAt).slice(0,8);$("activeRentals").innerHTML=active.length?active.map(r=>`<div class="list-row"><div><strong>${esc(r.equipmentName||r.equipment||"Equipment")}</strong><br><small>${esc(r.customerName||"Customer")}</small></div><div><small>Due</small><br><strong>${esc(fmt(r.endAt||r.expectedReturnAt))}</strong></div></div>`).join(""):`<div class="empty">No equipment is currently out.</div>`;
 const upcoming=state.reservations.filter(r=>new Date(r.endAt||r.startAt||0)>=new Date()).sort((a,b)=>new Date(a.startAt||0)-new Date(b.startAt||0)).slice(0,8);$("upcomingReservations").innerHTML=upcoming.length?upcoming.map(r=>`<div class="list-row"><div><strong>${esc(r.equipmentName||"Equipment")}</strong><br><small>${esc(r.customerName||"Customer")}</small></div><strong>${esc(fmt(r.startAt))}</strong></div>`).join(""):`<div class="empty">No upcoming reservations.</div>`}

function renderEquipment(){const q=($("equipmentSearch")?.value||state.search||"").toLowerCase();const filter=$("statusFilter")?.value||"";const rows=state.equipment.filter(e=>`${e.name||""} ${e.category||""} ${e.brand||""} ${e.model||""}`.toLowerCase().includes(q)&&(!filter||equipmentStatus(e)===filter));$("equipmentGrid").innerHTML=rows.length?rows.map(e=>{const status=equipmentStatus(e);return `<article class="equipment-card"><div class="equipment-photo">${e.photoUrl||e.imageUrl?`<img src="${esc(imageUrl(e.photoUrl||e.imageUrl))}" alt="${esc(e.name)}">`:`<div class="muted">No photo</div>`}</div><div class="equipment-body"><span class="badge ${status}">${status}</span><h3>${esc(e.name||"Unnamed equipment")}</h3><p class="muted">${esc(e.category||"")}</p><div class="card-actions"><button data-edit-equipment="${e.id}">Edit</button><button class="secondary" data-qr-equipment="${e.id}">QR Code</button><button class="secondary" data-preview-equipment="${e.id}">Preview Portal</button></div></div></article>`}).join(""):`<div class="empty">No equipment found.</div>`;document.querySelectorAll("[data-edit-equipment]").forEach(b=>b.onclick=()=>equipmentForm(state.equipment.find(e=>e.id===b.dataset.editEquipment)));document.querySelectorAll("[data-qr-equipment]").forEach(b=>b.onclick=()=>showQr(state.equipment.find(e=>e.id===b.dataset.qrEquipment)));document.querySelectorAll("[data-preview-equipment]").forEach(b=>b.onclick=()=>window.open(customerUrl(b.dataset.previewEquipment),"_blank"))}

function table(rows,columns){if(!rows.length)return`<div class="empty">No records found.</div>`;return`<table><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${esc(typeof c.value==="function"?c.value(r):r[c.value]||"")}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function renderCustomers(){$("customersTable").innerHTML=table(state.customers,[{label:"Name",value:r=>r.name||`${r.firstName||""} ${r.lastName||""}`.trim()},{label:"Phone",value:"phone"},{label:"Email",value:"email"},{label:"City",value:"city"}])}
function renderRentals(){$("rentalsTable").innerHTML=table(state.rentals,[{label:"Equipment",value:r=>r.equipmentName||r.equipment||""},{label:"Customer",value:"customerName"},{label:"Start",value:r=>fmt(r.startAt)},{label:"Return",value:r=>r.actualReturnAt?fmt(r.actualReturnAt):"Currently out"}])}
function renderReservations(){$("reservationsTable").innerHTML=table(state.reservations,[{label:"Equipment",value:"equipmentName"},{label:"Customer",value:"customerName"},{label:"Starts",value:r=>fmt(r.startAt)},{label:"Status",value:"status"}])}
function renderMaintenance(){$("maintenanceTable").innerHTML=table(state.maintenance,[{label:"Equipment",value:"equipmentName"},{label:"Service",value:r=>r.description||r.serviceType||r.notes||""},{label:"Date",value:r=>fmt(r.date||r.createdAt)},{label:"Cost",value:r=>r.cost?`$${Number(r.cost).toFixed(2)}`:""}])}

function parseLines(value){return String(value||"").split("\n").map(x=>x.trim()).filter(Boolean)}
function equipmentForm(e={}){openModal(e.id?`Edit ${e.name||"Equipment"}`:"Add Equipment",`<form id="equipmentForm"><div class="form-grid"><div><label>Name</label><input id="eqName" value="${esc(e.name||"")}" required></div><div><label>Category</label><input id="eqCategory" value="${esc(e.category||"")}"></div><div><label>Brand</label><input id="eqBrand" value="${esc(e.brand||"")}"></div><div><label>Model</label><input id="eqModel" value="${esc(e.model||"")}"></div><div><label>Photo URL</label><input id="eqPhoto" value="${esc(e.photoUrl||e.imageUrl||"")}"></div><div><label>Manual URL</label><input id="eqManual" value="${esc(e.manualUrl||"")}"></div></div><div class="form-section"><h3>Customer Portal</h3><label>Before You Start — one item per line</label><textarea id="eqBeforeStart">${esc((e.beforeStart||[]).join?e.beforeStart.join("\n"):e.beforeStart||"")}</textarea><label>Before Returning — one item per line</label><textarea id="eqBeforeReturn">${esc((e.beforeReturn||[]).join?e.beforeReturn.join("\n"):e.beforeReturn||"")}</textarea><label>Included Accessories — one item per line</label><textarea id="eqIncluded">${esc((e.includedAccessories||[]).join?e.includedAccessories.join("\n"):e.includedAccessories||"")}</textarea><label>Safety Instructions</label><textarea id="eqSafety">${esc(e.safetyInstructions||e.customerInstructions||"")}</textarea><label>Video links — one URL per line</label><textarea id="eqVideos">${esc((e.videoUrls||[]).join?e.videoUrls.join("\n"):e.videoUrls||"")}</textarea><label>Document links — use “Title | URL”, one per line</label><textarea id="eqDocuments">${esc((e.documents||[]).map(d=>`${d.title||"Document"} | ${d.url||""}`).join("\n"))}</textarea></div><div class="button-row"><button type="submit">Save Equipment</button><button type="button" id="cancelEquipment" class="secondary">Cancel</button></div></form>`);$("cancelEquipment").onclick=closeModal;$("equipmentForm").onsubmit=async event=>{event.preventDefault();const documents=parseLines($("eqDocuments").value).map(line=>{const [title,...rest]=line.split("|");return{title:(title||"Document").trim(),url:rest.join("|").trim()}}).filter(x=>x.url);const payload={name:$("eqName").value.trim(),category:$("eqCategory").value.trim(),brand:$("eqBrand").value.trim(),model:$("eqModel").value.trim(),photoUrl:$("eqPhoto").value.trim(),manualUrl:$("eqManual").value.trim(),beforeStart:parseLines($("eqBeforeStart").value),beforeReturn:parseLines($("eqBeforeReturn").value),includedAccessories:parseLines($("eqIncluded").value),safetyInstructions:$("eqSafety").value.trim(),videoUrls:parseLines($("eqVideos").value),documents,updatedAt:serverTimestamp()};try{let id=e.id;if(id)await updateDoc(doc(db,"equipment",id),payload);else{id=(await addDoc(collection(db,"equipment"),{...payload,createdAt:serverTimestamp()})).id}await publishEquipment(id,{id,...e,...payload});toast("Equipment saved");closeModal()}catch(error){alert(error.message)}}}

function customerUrl(id){const url=new URL("./customer.html",window.location.href);url.searchParams.set("equipment",id);return url.toString()}
async function loadQr(){if(window.QRCode)return;await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js";s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function showQr(e){await publishEquipment(e.id,e);await loadQr();openModal(`QR Code — ${e.name}`,`<div style="text-align:center"><img src="./mcgriffs-logo.png" style="width:220px;height:110px;object-fit:contain"><h3>${esc(e.name)}</h3><div id="qrBox" style="display:inline-block;padding:14px;background:#fff"></div><p><strong>Scan for status, manuals, videos, and instructions</strong></p><div class="button-row" style="justify-content:center"><button id="copyQrLink" class="secondary">Copy Link</button><button id="openQrLink">Open Portal</button></div></div>`);new QRCode($("qrBox"),{text:customerUrl(e.id),width:260,height:260,correctLevel:QRCode.CorrectLevel.H});$("copyQrLink").onclick=async()=>{await navigator.clipboard.writeText(customerUrl(e.id));toast("Portal link copied")};$("openQrLink").onclick=()=>window.open(customerUrl(e.id),"_blank")}

async function publishEquipment(id,e){const rental=activeRental(id);const reservation=activeReservation(id);const status=equipmentStatus({...e,id});const publicRecord={equipmentId:id,name:e.name||"Equipment",category:e.category||"",brand:e.brand||"",model:e.model||"",photoUrl:e.photoUrl||e.imageUrl||"",status,expectedReturnAt:rental?.endAt||rental?.expectedReturnAt||"",reservedStartAt:reservation?.startAt||"",manualUrl:e.manualUrl||"",beforeStart:e.beforeStart||[],beforeReturn:e.beforeReturn||[],includedAccessories:e.includedAccessories||[],safetyInstructions:e.safetyInstructions||e.customerInstructions||"",videoUrls:e.videoUrls||[],documents:e.documents||[],supportPhone:state.settings.phone||"641-637-4010",updatedAt:serverTimestamp()};await setDoc(doc(db,"publicEquipment",id),publicRecord,{merge:true})}
async function syncPublicEquipment(){if(!auth.currentUser)return;for(const e of state.equipment){try{await publishEquipment(e.id,e)}catch(error){console.warn("Public portal sync skipped:",error.message);break}}}

function listenCollection(name,key){onSnapshot(collection(db,name),snap=>{state[key]=snap.docs.map(d=>({id:d.id,...d.data()}));render();if(name==="equipment"||name==="rentals"||name==="reservations")clearTimeout(window.__syncTimer),window.__syncTimer=setTimeout(syncPublicEquipment,1200)},error=>console.error(name,error))}
function startListeners(){listenCollection("equipment","equipment");listenCollection("customers","customers");listenCollection("rentals","rentals");listenCollection("reservations","reservations");listenCollection("maintenance","maintenance");onSnapshot(doc(db,"settings","business"),snap=>{state.settings=snap.exists()?snap.data():{};render()})}

function wire(){document.querySelectorAll("[data-profile]").forEach(b=>b.onclick=()=>{selectedProfile=profiles[b.dataset.profile];$("profileName").textContent=selectedProfile.name;document.querySelector(".profile-grid").classList.add("hidden");$("passwordPanel").classList.remove("hidden");$("passwordInput").focus()});$("backButton").onclick=()=>{$("passwordPanel").classList.add("hidden");document.querySelector(".profile-grid").classList.remove("hidden")};$("loginButton").onclick=async()=>{if(!selectedProfile)return;$("loginError").textContent="";try{await signInWithEmailAndPassword(auth,selectedProfile.email,$("passwordInput").value);state.profile=selectedProfile}catch(error){$("loginError").textContent="Incorrect password or login failed."}};$("passwordInput").addEventListener("keydown",e=>{if(e.key==="Enter")$("loginButton").click()});$("logoutButton").onclick=()=>signOut(auth);document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("closeModal").onclick=closeModal;$("modal").addEventListener("click",e=>{if(e.target===$("modal"))closeModal()});$("addEquipmentButton").onclick=()=>equipmentForm();$("equipmentSearch").oninput=renderEquipment;$("statusFilter").onchange=renderEquipment;$("globalSearch").oninput=e=>{state.search=e.target.value;$("equipmentSearch").value=e.target.value;setView("equipment");renderEquipment()}}
wire();onAuthStateChanged(auth,user=>{if(user){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");const profile=Object.values(profiles).find(p=>p.email===user.email)||state.profile||profiles.manager;state.profile=profile;$("userBadge").textContent=profile.name.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();startListeners()}else{$("appView").classList.add("hidden");$("loginView").classList.remove("hidden")}});
